apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-demo-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: demoApp
    spec:
      containers:
        - name: docker-demo-container
          image: ohmygodluke/docker-demo-app:latest
          ports:
            - containerPort: 3000
  selector:
    matchLabels:
      app: demoApp
